name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd client && npm ci
          cd ../server && npm ci
          cd ../electron && npm ci

      - name: Build client
        run: cd client && npm run build

      - name: Build server
        run: cd server && npm run build

      - name: Build and publish Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd electron
          npm run publish
